---
title: "Group A CA pollution burden"
author: "Satie Airame and Allison Horst"
date: "11/28/2020"
output: html_document
---

## CalEnviroScreen 3.0
## About the data: https://caleja.org/wp-content/uploads/2015/09/CES3.0-5.pdf
## Live coding with Allison

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
```

# Read in the ces3demographics.csv data

```{r}
ces <- read_csv(here("data", "ces3demographics.csv")) %>% 
  clean_names()
```

# Add a scatterplot 

```{r}
ggplot(data = ces, aes(x = white_percent, y = ces_3_0_score)) +
  geom_hex() +
  labs(x = "Percent white (%)",
       y = "Pollution Burden Score",
       title = "Pollution burden score relative to percent white population in California") +
  scale_fill_gradient(low = "navy", high = "orange") +
  theme_minimal()
```
In California census tracts, there is a clear trend toward higher pollution burden (by CES3.0 Score) as the percentage of residents identifying as white decreases.

Good job Satie! 
